package modelo;
// Generated 18/08/2018 11:53:09 by Hibernate Tools 4.3.1



/**
 * Sosa98Id generated by hbm2java
 */
public class Sosa98Id  implements java.io.Serializable {


     private String tenumero;
     private String tenumseq;

    public Sosa98Id() {
    }

    public Sosa98Id(String tenumero, String tenumseq) {
       this.tenumero = tenumero;
       this.tenumseq = tenumseq;
    }
    public Sosa98Id(String tenumero) {
       this.tenumero = tenumero;
    }
   
    public String getTenumero() {
        return this.tenumero;
    }
    
    public void setTenumero(String tenumero) {
        this.tenumero = tenumero;
    }
    public String getTenumseq() {
        return this.tenumseq;
    }
    
    public void setTenumseq(String tenumseq) {
        this.tenumseq = tenumseq;
    }




}


