package modelo;
// Generated 18/08/2018 11:53:09 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Objects;

/**
 * Sosa98 generated by hbm2java
 */
public class Sosa98 implements java.io.Serializable {

    private Sosa98Id id;
    private String tecomand;
    private String terefere;
    private Double tequanti;
    private Date   tedatcom;
    private String tevended;
    private String teobserv;
    private String tecdmesa;
    private String testatus;
    private String teimprim;
    private String tepedido;

    public Sosa98() {
    }

    public Sosa98(Sosa98Id id, String tecomand, String terefere, Date tedatcom) {
        this.id = id;
        this.tecomand = tecomand;
        this.terefere = terefere;
        this.tedatcom = tedatcom;
    }

    public Sosa98(Sosa98Id id, String tecomand, String terefere, Double tequanti, Date tedatcom, String tevended, String teobserv, String tecdmesa, String testatus, String teimprim, String tepedido) {
        this.id = id;
        this.tecomand = tecomand;
        this.terefere = terefere;
        this.tequanti = tequanti;
        this.tedatcom = tedatcom;
        this.tevended = tevended;
        this.teobserv = teobserv;
        this.tecdmesa = tecdmesa;
        this.testatus = testatus;
        this.teimprim = teimprim;
        this.tepedido = tepedido;
    }
    
    public Sosa98Id getId() {
        return this.id;
    }

    public void setId(Sosa98Id id) {
        this.id = id;
    }

    public String getTecomand() {
        return this.tecomand;
    }

    public void setTecomand(String tecomand) {
        this.tecomand = tecomand;
    }

    public String getTerefere() {
        return this.terefere;
    }

    public void setTerefere(String terefere) {
        this.terefere = terefere;
    }

    public Double getTequanti() {
        return this.tequanti;
    }

    public void setTequanti(Double tequanti) {
        this.tequanti = tequanti;
    }

    public Date getTedatcom() {
        return this.tedatcom;
    }

    public void setTedatcom(Date tedatcom) {
        this.tedatcom = tedatcom;
    }

    public String getTevended() {
        return this.tevended;
    }

    public void setTevended(String tevended) {
        this.tevended = tevended;
    }

    public String getTeobserv() {
        return this.teobserv;
    }

    public void setTeobserv(String teobserv) {
        this.teobserv = teobserv;
    }

    public String getTecdmesa() {
        return this.tecdmesa;
    }

    public void setTecdmesa(String tecdmesa) {
        this.tecdmesa = tecdmesa;
    }

    public String getTestatus() {
        return testatus;
    }

    public void setTestatus(String testatus) {
        this.testatus = testatus;
    }

    public String getTeimprim() {
        return teimprim;
    }

    public void setTeimprim(String teimprim) {
        this.teimprim = teimprim;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 79 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Sosa98 other = (Sosa98) obj;
        return Objects.equals(this.id, other.id);
    }

    public String getTepedido() {
        return tepedido;
    }

    public void setTepedido(String tepedido) {
        this.tepedido = tepedido;
    }

    @Override
    public String toString() {
        return "Sosa98{" + "id=" + id + ", tecomand=" + tecomand + ", terefere=" + terefere + ", tequanti=" + tequanti + ", tedatcom=" + tedatcom + ", tevended=" + tevended + ", teobserv=" + teobserv + ", tecdmesa=" + tecdmesa + ", testatus=" + testatus + ", teimprim=" + teimprim + ", tepedido=" + tepedido + '}';
    }

}
